<%@ Page Language="C#" MasterPageFile="~/adminhome.master" AutoEventWireup="true" CodeFile="uploadfile.aspx.cs" Inherits="uploadfile" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style1
        {
            width: 88%;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p>
        <br />
    </p>
       <center> &nbsp;&nbsp; <asp:Label ID="Label2" runat="server" 
            style="font-family: 'Blackadder ITC'; font-size: xx-large; color: #660033" 
            Text="File Upload"></asp:Label></center>
    <asp:Panel ID="Panel2" runat="server" BorderColor="#660033" 
        BorderStyle="Groove" Height="138px" style="margin-left: 395px" 
        Width="617px">
        <table class="style1">
            <tr>
                <td>
                    File Catagory</td>
                <td>
                    <asp:TextBox ID="TextBox1" runat="server" Height="25px" Width="136px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>
                    FileName</td>
                <td>
                    <asp:TextBox ID="TextBox2" runat="server" Height="25px" Width="136px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>
                    File Upload</td>
                <td>
                    <asp:FileUpload ID="FileUpload1" runat="server" Height="25px" Width="220px" />
                    
                </td>
            </tr>
            <tr>
                <td>
                    &nbsp;</td>
                <td>
                    <asp:Button ID="Button1" runat="server" BackColor="#36B0B6" ForeColor="White" 
                        Height="31px" Text="File Upload" Width="140px" onclick="Button1_Click" />
                    <asp:Label ID="Label3" runat="server" 
                        style="font-family: 'Blackadder ITC'; font-size: x-large"></asp:Label>
                </td>
            </tr>
        </table>
    </asp:Panel>
    <p>
    </p>
      <center>  
          <asp:GridView ID="GridView1" runat="server" ForeColor="Black" Height="143px" 
            Width="377px" AutoGenerateDeleteButton="True" 
              onrowdeleting="GridView1_RowDeleting">
              <Columns>
                  <asp:TemplateField HeaderText="fileid">
                      <EditItemTemplate>
                          <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("fileid") %>'></asp:TextBox>
                      </EditItemTemplate>
                      <ItemTemplate>
                          <asp:Label ID="Label1" runat="server" Text='<%# Bind("fileid") %>'></asp:Label>
                      </ItemTemplate>
                  </asp:TemplateField>
              </Columns>
            <HeaderStyle BackColor="#660033" ForeColor="White" />
        </asp:GridView></center>
    </p>
    </asp:Content>

